// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using fiap.Data;

#nullable disable

namespace fiap.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fiap.Models.ColetaModel", b =>
                {
                    b.Property<int>("ColetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColetaId"));

                    b.Property<DateTime>("dataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("rota")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ColetaId");

                    b.ToTable("tb_coleta", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
